export const sepayContent = {
  accountLabel: "Số tài khoản",
  amountLabel: "Số tiền",
  bankLabel: "Ngân hàng",
  close: "Đóng",
  contentLabel: "Nội dung chuyển khoản",
  contentWarning: "Giữ nguyên nội dung chuyển khoản, sai nội dung thì hệ thống không tự xác nhận được.",
  copied: "Đã sao chép",
  copy: "Sao chép",
  done: "Xong",
  expired: "Mã QR đã hết hạn. Hãy đóng lại và tạo giao dịch mới.",
  expiresIn: (label: string) => `Mã QR còn hiệu lực ${label}`,
  failed: "Giao dịch không thành công.",
  holderLabel: "Chủ tài khoản",
  loading: "Đang tạo mã thanh toán…",
  partial: (remaining: string) => `Đã nhận tiền nhưng chưa đủ. Vui lòng chuyển thêm ${remaining}.`,
  paid: "Đã nhận được tiền. Cảm ơn bạn!",
  qrHint: "Mở app ngân hàng, quét mã QR bên dưới để thanh toán.",
  remainingLabel: "Số tiền cần chuyển",
  title: "Thanh toán qua SePay",
  waiting: "Đang chờ chuyển khoản…",
};
