import type {
  BookingScheduleConfig,
  BookingScheduleContent,
  BookingStatus,
} from "@/components/booking/BookingSchedule/types";

export const bookingStatusOptions: BookingStatus[] = ["pending", "confirmed", "checked-in", "completed", "cancelled"];

export const bookingScheduleConfig: BookingScheduleConfig = {
  endMinute: 22 * 60,
  initialDate: "2026-08-15",
  slotMinutes: 60,
  startMinute: 6 * 60,
};

export const bookingScheduleContent: BookingScheduleContent = {
  addBookingLabel: "Thêm lịch",
  allCourtsLabel: "Tất cả sân",
  allStatusesLabel: "Tất cả trạng thái",
  bookingCodeLabel: "Mã đặt sân",
  bookingCreatedMessage: "Lịch đặt sân đã được thêm vào dữ liệu mẫu.",
  bookingDetailLabel: "Chi tiết đặt sân",
  bookingStatusLabels: {
    cancelled: "Đã huỷ",
    "checked-in": "Đã nhận sân",
    completed: "Hoàn thành",
    confirmed: "Đã xác nhận",
    pending: "Chờ xác nhận",
  },
  cancelBookingLabel: "Huỷ lịch",
  closeLabel: "Đóng",
  confirmBookingLabel: "Xác nhận lịch",
  courtFilterLabel: "Lọc theo sân",
  courtStatusLabels: {
    available: "Đang hoạt động",
    inactive: "Tạm ngưng",
    maintenance: "Bảo trì",
  },
  createBookingDescription: "Nhập thông tin khách hàng cho khung giờ đã chọn.",
  createBookingLabel: "Tạo lịch đặt sân",
  customerLabel: "Khách hàng",
  customerNameLabel: "Tên khách hàng",
  customerNamePlaceholder: "Nguyễn Văn A",
  customerPhoneLabel: "Số điện thoại",
  customerPhonePlaceholder: "0901 234 567",
  dateLabel: "Ngày đặt sân",
  emptyBookingsLabel: "Không có lịch đặt sân phù hợp với bộ lọc.",
  filterLabel: "Bộ lọc lịch đặt sân",
  indoorLabel: "Sân trong nhà",
  locationLabel: "12 Nguyễn Khánh Toàn, Cầu Giấy, Hà Nội",
  nextDateLabel: "Ngày tiếp theo",
  noteLabel: "Ghi chú",
  notePlaceholder: "Yêu cầu thêm của khách hàng",
  paymentLabel: "Thanh toán",
  paymentStatusLabels: {
    failed: "Thất bại",
    paid: "Đã thanh toán",
    partial: "Đã đặt cọc",
    refunded: "Đã hoàn tiền",
    unpaid: "Chưa thanh toán",
  },
  previousDateLabel: "Ngày trước đó",
  priceLabel: "Tổng tiền",
  scheduleLabel: "Lịch sân tennis theo thời gian",
  searchLabel: "Tìm lịch đặt sân",
  searchPlaceholder: "Mã lịch hoặc tên khách hàng",
  selectedDateLabel: "Chọn ngày xem lịch",
  slotLabel: "Khung giờ trống",
  statusFilterLabel: "Lọc theo trạng thái",
  statusLabel: "Trạng thái",
  surfaceLabels: {
    clay: "Sân đất nện",
    hard: "Sân cứng",
    synthetic: "Sân cỏ nhân tạo",
  },
  timeLabel: "Thời gian",
  title: "Quản lý lịch đặt sân",
  totalBookingsLabel: "Lịch trong ngày",
  totalCourtsLabel: "Sân hoạt động",
  venueName: "TennisHub Cầu Giấy",
};
