export const forgotPasswordContent = {
  backToLookup: "Đổi tài khoản khác",
  codeLabel: "Mã xác thực",
  codePlaceholder: "Nhập mã gồm 6 số",
  codeSent: "Mã xác thực đã gửi (bản dev hiển thị trực tiếp):",
  confirmPasswordLabel: "Nhập lại mật khẩu mới",
  confirmPasswordPlaceholder: "Nhập lại mật khẩu mới",
  continue: "Tiếp tục",
  errorMessage: "Không gửi được mã xác thực",
  countryCode: "+ 84",
  description: "Nhập email hoặc số điện thoại đã đăng ký để tìm kiếm và lấy lại mật khẩu.",
  email: "Email",
  emailLabel: "Email đã đăng ký",
  emailPlaceholder: "Nhập email đã đăng ký",
  expiresNote: (minutes: number) => `Mã có hiệu lực trong ${minutes} phút.`,
  fanpage: "Fanpage",
  mismatchMessage: "Hai lần nhập mật khẩu chưa khớp nhau",
  passwordLabel: "Mật khẩu mới",
  passwordPlaceholder: "Ít nhất 6 ký tự",
  resendLabel: "Gửi lại mã",
  resetDescription: "Nhập mã xác thực vừa nhận cùng mật khẩu mới cho tài khoản của bạn.",
  resetErrorMessage: "Không đặt lại được mật khẩu",
  resetSubmit: "Đặt lại mật khẩu",
  resetSuccess: "Đổi mật khẩu thành công, đang chuyển tới trang đăng nhập…",
  shortPasswordMessage: "Mật khẩu phải có ít nhất 6 ký tự",
  // Chưa có contract link hỗ trợ; để trống thì nút tắt thay vì mở URL giả.
  fanpageUrl: "",
  phone: "Số điện thoại",
  phoneLabel: "Số điện thoại đã đăng ký",
  phonePlaceholder: "Nhập số điện thoại đã đăng ký",
  supportDescription: "Bạn gặp vấn đề hoặc cần hỗ trợ? Vui lòng liên hệ với chúng tôi qua Zalo hoặc Fanpage để được hỗ trợ",
  title: "Quên mật khẩu",
  lookupTitle: "Tìm kiếm tài khoản theo",
  zalo: "Zalo",
  zaloUrl: "",
};
