export const forgotPasswordContent = {
  continue: "Tiếp tục",
  countryCode: "+ 84",
  description: "Nhập email hoặc số điện thoại đã đăng ký để tìm kiếm và lấy lại mật khẩu.",
  email: "Email",
  emailLabel: "Email đã đăng ký",
  emailPlaceholder: "Nhập email đã đăng ký",
  fanpage: "Fanpage",
  phone: "Số điện thoại",
  phoneLabel: "Số điện thoại đã đăng ký",
  phonePlaceholder: "Nhập số điện thoại đã đăng ký",
  supportDescription: "Bạn gặp vấn đề hoặc cần hỗ trợ? Vui lòng liên hệ với chúng tôi qua Zalo hoặc Fanpage để được hỗ trợ",
  title: "Quên mật khẩu",
  lookupTitle: "Tìm kiếm tài khoản theo",
  zalo: "Zalo",
};
